import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./styles/globals.scss";
import DynamicBackground from "./components/DynamicBackground/DynamicBackground";
import NavBar from "./components/NavBar/NavBar";
import PageInfoOverlay from "./components/PageInfoOverlay/PageInfoOverlay";
import RouteTransitionWrapper from "./components/RouteTransitionWrapper/RouteTransitionWrapper";

const outfit = Outfit({ 
  subsets: ['latin'], 
  weight: ['400','600'], 
  variable: '--font-outfit' 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.variable}>
        
        <DynamicBackground />

        <PageInfoOverlay />

        <NavBar />

        <main>
          <RouteTransitionWrapper>
            {children}
          </RouteTransitionWrapper>
        </main>

      </body>
    </html>
  );
}
