import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./styles/globals.scss";
import NavBar from "./components/NavBar/NavBar";
import RouteTransitionWrapper from "./components/RouteTransitionWrapper/RouteTransitionWrapper";
import Footer from "./components/Footer/Footer";
import FadeBackground from "./components/FadeBackground/FadeBackground";
import Aurora from "./components/AnimatedGradientBackdrop/Aurora";


const outfit = Outfit({ 
  subsets: ['latin'], 
  weight: ['400','600'], 
  variable: '--font-outfit' 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.variable}>

        {/* <FadeBackground /> */}

        <Aurora />

        <NavBar />

        <main>
          <RouteTransitionWrapper>
            {children}
          </RouteTransitionWrapper>
        </main>

        <Footer />

      </body>
    </html>
  );
}
