import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./styles/globals.scss";
import DynamicBackground from "./components/DynamicBackground/DynamicBackground";
import NavBar from "./components/NavBar/NavBar";

const outfit = Outfit({ 
  subsets: ['latin'], 
  weight: ['400','600'], 
  variable: '--font-outfit' 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.variable}>
        <DynamicBackground />
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
