// schemas/logoBrandingFields.ts
import { defineField } from 'sanity'
import { makeTeaserFields, makeOutcomesFields, makeKeyLearningsFields, makeWhatWorkedFields } from './shared/fieldGroups'

export const logoBrandingFields = [
  // ===== Teaser Image Section =========================================================
  ...makeTeaserFields('', 'Logos & Branding'),

  // ===== Business Context ===============================================================
  defineField({
    name: 'businessContextHeading',
    title: 'Business Context Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Business Context section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'businessContextContent',
    title: 'Business Context Content',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text content explaining Business Context findings',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Problems Identified ===============================================================
  defineField({
    name: 'problemsIdentifiedHeading',
    title: 'Problems Identified Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Brand Problems identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'problemsIdentified',
    title: 'Problems Identified',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of Brand Problems identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'problemsIdentifiedImage',
    title: 'Problems Identified Image',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'problemsIdentifiedVideo',
    title: 'Problems Identified Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'problemsIdentifiedVideoPoster',
    title: 'Problems Identified Video Poster',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Design Objectives ===============================================================
  defineField({
    name: 'designObjectivesHeading',
    title: 'Design Objectives Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Brand Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designObjectives',
    title: 'Design Objectives',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of Brand Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designObjectivesImage',
    title: 'Design Objectives Image',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designObjectivesVideo',
    title: 'Design Objectives Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designObjectivesVideoPoster',
    title: 'Design Objectives Video Poster',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Design Approach Section =========================================================
  defineField({
    name: 'designApproachHeading',
    title: 'Design Approach Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for design approach section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'discoveryStrategyHeading',
    title: 'Discovery Strategy Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Discovery Strategy section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'discoveryStrategy',
    title: 'Discovery Strategy',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text explaining the project discovery stategy',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designApproachMethods',
    title: 'Design Approach Methods',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: [
          { name: 'approachTitle', title: 'Design Approach Title', type: 'string', description: 'e.g., "Market Analysis", "Positioning"' },
          { name: 'approachDescription', title: 'Design Approach Description', type: 'text', rows: 2, description: 'Description of what the method entails' },
        ],
      },
    ],
    description: 'List of Design approach methods and their details',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== First Core Section =========================================================
  defineField({
    name: 'firstCoreSectionHeading',
    title: 'First Core Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreSectionText',
    title: 'First Core Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreSectionList',
    title: 'First Core Section List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreLandscapeImages',
    title: 'First Core Section Landscape Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Landscape Images for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreLandscapeVideos',
    title: 'First Core Section Landscape Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Landscape Videos for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreLandscapeVideoPosters',
    title: 'First Core Section Landscape Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for landscape Videos for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCorePortraitImages',
    title: 'First Core Section Portrait Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Portrait Images for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCorePortraitVideos',
    title: 'First Core Section Portrait Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Portrait Videos for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCorePortraitVideoPosters',
    title: 'First Core Section Portrait Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for portrait Videos for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Second Core Section =========================================================
  defineField({
    name: 'secondCoreSectionHeading',
    title: 'Second Core Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreSectionText',
    title: 'Second Core Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreSectionList',
    title: 'Second Core Section List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreLandscapeImages',
    title: 'Second Core Section Landscape Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Landscape Images for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreLandscapeVideos',
    title: 'Second Core Section Landscape Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Landscape Videos for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreLandscapeVideoPosters',
    title: 'Second Core Section Landscape Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for landscape Videos for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCorePortraitImages',
    title: 'Second Core Section Portrait Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Portrait Images for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCorePortraitVideos',
    title: 'Second Core Section Portrait Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Portrait Videos for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCorePortraitVideoPosters',
    title: 'Second Core Section Portrait Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for portrait Videos for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Third Core Section =========================================================
  defineField({
    name: 'thirdCoreSectionHeading',
    title: 'Third Core Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreSectionText',
    title: 'Third Core Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreSectionList',
    title: 'Third Core Section List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreLandscapeImages',
    title: 'Third Core Section Landscape Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Landscape Images for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreLandscapeVideos',
    title: 'Third Core Section Landscape Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Landscape Videos for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreLandscapeVideoPosters',
    title: 'Third Core Section Landscape Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for landscape Videos for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCorePortraitImages',
    title: 'Third Core Section Portrait Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Portrait Images for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCorePortraitVideos',
    title: 'Third Core Section Portrait Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Portrait Videos for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCorePortraitVideoPosters',
    title: 'Third Core Section Portrait Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for portrait Videos for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Outcomes Section =========================================================
  ...makeOutcomesFields('', 'Logos & Branding'),

  // ===== Key Learnings Section ===============================================================
  ...makeKeyLearningsFields('', 'Logos & Branding'),

  // ===== What Worked Section ===============================================================
  ...makeWhatWorkedFields('', 'Logos & Branding'),
]
