// schemas/logoBrandingFields.ts
import { defineField } from 'sanity'

export const logoBrandingFields = [
  // ===== Teaser Image Section =========================================================
  defineField({
    name: 'teaserImages',
    title: 'Teaser Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Images showing early teasers of the final designs',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Business Context ===============================================================
  defineField({
    name: 'businessContextHeading',
    title: 'Business Context Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Business Context section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'businessContextContent',
    title: 'Business Context Content',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text content explaining Business Context findings',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Problems Identified ===============================================================
  defineField({
    name: 'problemsIdentifiedHeading',
    title: 'Problems Identified Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Brand Problems identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'problemsIdentified',
    title: 'Problems Identified',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of Brand Problems identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'problemsIdentifiedImage',
    title: 'Problems Identified Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Design Objectives ===============================================================
  defineField({
    name: 'designObjectivesHeading',
    title: 'Design Objectives Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Brand Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designObjectives',
    title: 'Design Objectives',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of Brand Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designObjectivesImage',
    title: 'Design Objectives Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Design Approach Section =========================================================
  defineField({
    name: 'designApproachHeading',
    title: 'Design Approach Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for design approach section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'discoveryStrategyHeading',
    title: 'Discovery Strategy Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Discovery Strategy section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'discoveryStrategy',
    title: 'Discovery Strategy',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text explaining the project discovery stategy',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'designApproachMethods',
    title: 'Design Approach Methods',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: [
          { name: 'approachTitle', title: 'Design Approach Title', type: 'string', description: 'e.g., "Market Analysis", "Positioning"' },
          { name: 'approachDescription', title: 'Design Approach Description', type: 'text', rows: 2, description: 'Description of what the method entails' },
        ],
      },
    ],
    description: 'List of Design approach methods and their details',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== First Core Section =========================================================
  defineField({
    name: 'firstCoreSectionHeading',
    title: 'First Core Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreSectionText',
    title: 'First Core Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreSectionList',
    title: 'First Core Section List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCoreLandscapeImages',
    title: 'First Core Section Landscape Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Landscape Images for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'firstCorePortraitImages',
    title: 'First Core Section Portrait Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Portrait Images for the first core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  
  // ===== Second Core Section =========================================================
  defineField({
    name: 'secondCoreSectionHeading',
    title: 'Second Core Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreSectionText',
    title: 'Second Core Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreSectionList',
    title: 'Second Core Section List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCoreLandscapeImages',
    title: 'Second Core Section Landscape Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Landscape Images for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'secondCorePortraitImages',
    title: 'Second Core Section Portrait Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Portrait Images for the second core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Third Core Section =========================================================
  defineField({
    name: 'thirdCoreSectionHeading',
    title: 'Third Core Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreSectionText',
    title: 'Third Core Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreSectionList',
    title: 'Third Core Section List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCoreLandscapeImages',
    title: 'Third Core Section Landscape Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Landscape Images for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'thirdCorePortraitImages',
    title: 'Third Core Section Portrait Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Portrait Images for the third core section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Outcomes Section =========================================================
  defineField({
    name: 'outcomesSectionHeading',
    title: 'Outcomes Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for outcomes section',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'mainOutcomeHeading',
    title: 'Main Outcome Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Main Outcome',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'mainOutcomeText',
    title: 'Main Outcome Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text explaining the main outcome',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'otherOutcomes',
    title: 'Other Outcomes',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: [
          { name: 'outcomeTitle', title: 'Outcome Title', type: 'string', description: 'e.g., "Strategic Impact", "Visual Impact"' },
          { name: 'outcomeDescription', title: 'Outcome Description', type: 'text', rows: 2, description: 'Description of what the outcome' },
        ],
      },
    ],
    description: 'List of Design approach methods and their details',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== Key Learnings Section ===============================================================
  defineField({
    name: 'keyLearnHeading',
    title: 'Key learnings Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Key Learnings',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'keyLearnText',
    title: 'Key Learnings Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for key learnings',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'keyLearnList',
    title: 'Key Learnings List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of key learnings',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'keyLearnImage',
    title: 'Key Learnings Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Key Learnings',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),

  // ===== What Worked Section ===============================================================
  defineField({
    name: 'whatWorkedHeading',
    title: 'What Worked Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for What Worked',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'whatWorkedText',
    title: 'What Worked Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for What Worked',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'whatWorkedList',
    title: 'What Worked List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of What Worked',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
  defineField({
    name: 'whatWorkedImage',
    title: 'What Worked Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting What Worked',
    hidden: ({ parent }) => parent?.categoryName !== 'Logos & Branding',
  }),
]
