// schemas/uxCaseStudyFields.ts
import { defineField } from 'sanity'

export const uxCaseStudyFields = [
  // ===== Platform Display Section =========================================================
  defineField({
    name: 'platformImages',
    title: 'Platform Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Images showing the design across different platforms (mobile, desktop, etc.)',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'platformVideos',
    title: 'Platform Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos showing the design across different platforms (mobile, desktop, etc.)',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'platformVideoPosters',
    title: 'Platform Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for videos showing the design across different platforms (mobile, desktop, etc.)',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Project Rationale Section =========================================================
  defineField({
    name: 'projectRationaleHeading',
    title: 'Project Rationale Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Project Rationale Section (e.g., "***Why I Designed This")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'projectRationale',
    title: 'Project Rationale',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of bullet points describing validated assumptions or key findings',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'projectRationaleImage',
    title: 'Project Rationale Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting rationale',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'projectRationaleVideo',
    title: 'Project Rationale Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting rationale',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'projectRationaleVideoPoster',
    title: 'Project Rationale Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting rationale',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Section Divider =========================================================
  defineField({
    name: 'researchSectionTitle',
    title: 'Research Section Title',
    type: 'string',
    group: 'project-specific',
    description: 'Large heading to divide major sections (e.g., "THE USER\'S PERSPECTIVE")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'researchSectionImage',
    title: 'Research Section Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'researchSectionVideo',
    title: 'Research Section Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'researchSectionVideoPoster',
    title: 'Research Section Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Market Research Section =========================================================
  defineField({
    name: 'marketResearchHeading',
    title: 'Market Research Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for market research section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'marketResearchContent',
    title: 'Market Research Content',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text content explaining market research findings',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'marketResearchVisual',
    title: 'Market Research Visual',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Chart, graph, or infographic supporting market research findings',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'marketResearchVisualVideo',
    title: 'Market Research Visual Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Chart, graph, or infographic supporting market research findings',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'marketResearchVisualVideoPoster',
    title: 'Market Research Visual Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for chart, graph, or infographic supporting market research findings',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Competitive Analysis Section =========================================================
  defineField({
    name: 'competitiveAnalysisHeading',
    title: 'Competitive Analysis Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for competitive analysis section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'competitiveAnalysisIntro',
    title: 'Competitive Analysis Introduction',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Introductory text explaining the competitive analysis approach',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'competitors',
    title: 'Competitors',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: [
          { name: 'competitorName', title: 'Competitor Name', type: 'string' },
          { name: 'competitorType', title: 'Competitor Type', type: 'string', description: 'e.g., "direct", "indirect"' },
          { name: 'competitorImage', title: 'Competitor Image', type: 'image', options: { hotspot: true }, description: 'Screenshot or visual of competitor product' },
          { name: 'competitorVideo', title: 'Competitor Video', type: 'file', options: { accept: 'video/mp4,video/webm' }, description: 'Screenshot or visual of competitor product' },
          { name: 'competitorVideoPoster', title: 'Competitor Video Poster', type: 'image', options: { hotspot: true }, description: 'Optional fallback poster image for screenshot or visual of competitor product' },
          { name: 'competitorPros', title: 'Competitor Pros', type: 'array', of: [{ type: 'string' }], description: 'List of pros/strengths' },
          { name: 'competitorCons', title: 'Competitor Cons', type: 'array', of: [{ type: 'string' }], description: 'List of cons/weaknesses' },
        ],
      },
    ],
    description: 'List of analyzed competitors with details',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'opportunitiesHeading',
    title: 'Opportunities Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for opportunities identified from research (e.g., "***Opportunities identified from benchmarking")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'opportunitiesList',
    title: 'Opportunities List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet point list of opportunities identified',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'opportunitiesImage',
    title: 'Opportunities Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Opportunities',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'opportunitiesVideo',
    title: 'Opportunities Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Opportunities',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'opportunitiesVideoPoster',
    title: 'Opportunities Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Opportunities',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== User Survey Section =========================================================
  defineField({
    name: 'userSurveyHeading',
    title: 'User Survey Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for user survey section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'userSurveyIntro',
    title: 'User Survey Introduction',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text explaining the survey methodology and target audience',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'surveyCharts',
    title: 'Survey Charts',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Charts/graphs showing survey results with titles and data',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'surveyChartsVideo',
    title: 'Survey Charts Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Charts/graphs showing survey results with titles and data',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'surveyChartsVideoPoster',
    title: 'Survey Charts Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for charts/graphs showing survey results with titles and data',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Assumption Validation Section =========================================================
  defineField({
    name: 'assumptionValidationHeading',
    title: 'Assumption Validation Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Assumption Validation Section (e.g., "***What The Research confirms")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'assumptionValidation',
    title: 'Assumption Validation',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of bullet points describing validated assumptions',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'assumptionValidationImage',
    title: 'Assumption Validation Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Assumption Validation',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'assumptionValidationVideo',
    title: 'Assumption Validation Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Assumption Validation',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'assumptionValidationVideoPoster',
    title: 'Assumption Validation Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Assumption Validation',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Key Insights & Opportunity Areas Section =========================================================
  defineField({
    name: 'keyInsightsHeading',
    title: 'Key Insights Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for key insights section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyInsights',
    title: 'Key Insights',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of key insights from research',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'opportunityText',
    title: 'Opportunity Identified',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text explaining what opportunity was identified',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== User Personas Section =========================================================
  defineField({
    name: 'personasHeading',
    title: 'User Personas Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for personas section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'personasIntro',
    title: 'Personas Introduction',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Introductory text explaining the personas created',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'personas',
    title: 'User Personas',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'List of user personas with detailed information',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'personasVideo',
    title: 'User Personas Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'List of user personas with detailed information',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'personasVideoPoster',
    title: 'User Personas Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for list of user personas with detailed information',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Problem Statement Section =========================================================
  defineField({
    name: 'problemStatementHeading',
    title: 'Problem Statement Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for problem statement section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'problemStatement',
    title: 'Problem Statement',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Clear articulation of the problem being solved',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Design Goals Section =========================================================
  defineField({
    name: 'designGoalsHeading',
    title: 'Design Goals Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for design goals section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'designGoals',
    title: 'Design Goals',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Numbered list of design goals and objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Ideation Section Divider =========================================================
  defineField({
    name: 'ideationSectionTitle',
    title: 'Ideation Section Title',
    type: 'string',
    group: 'project-specific',
    description: 'Large heading to divide major sections (e.g., "IDEATION & EARLY DESIGNS")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'ideationSectionImage',
    title: 'Ideation Section Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'ideationSectionVideo',
    title: 'Ideation Section Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'ideationSectionVideoPoster',
    title: 'Ideation Section Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== User Flow Section =========================================================
  defineField({
    name: 'userFlowHeading',
    title: 'User Flow Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for user flow section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'userFlowDescription',
    title: 'User Flow Description',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text describing the user flows mapped',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'userFlowDiagrams',
    title: 'User Flow Diagrams',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Flow diagrams showing user journeys',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'userFlowDiagramsVideo',
    title: 'User Flow Diagrams Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Flow diagrams showing user journeys',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'userFlowDiagramsVideoPoster',
    title: 'User Flow Diagrams Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for flow diagrams showing user journeys',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Information Architecture Section =========================================================
  defineField({
    name: 'informationArchitectureHeading',
    title: 'Information Architecture Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for information architecture section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'informationArchitectureDescription',
    title: 'Information Architecture Description',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text describing the IA approach and structure',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'informationArchitectureImage',
    title: 'Information Architecture Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Sitemap or IA diagram',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'informationArchitectureVideo',
    title: 'Information Architecture Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Sitemap or IA diagram',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'informationArchitectureVideoPoster',
    title: 'Information Architecture Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for sitemap or IA diagram',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Wireframes Section =========================================================
  defineField({
    name: 'wireframesHeading',
    title: 'Wireframes Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for wireframes section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'wireframesDescription',
    title: 'Wireframes Description',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text describing the wireframing process and iterations',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'wireframeImages',
    title: 'Wireframe Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Low-fidelity wireframe sketches or digital wireframes',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'wireframeVideos',
    title: 'Wireframe Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Low-fidelity wireframe sketches or digital wireframes',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'wireframeVideoPosters',
    title: 'Wireframe Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for low-fidelity wireframe sketches or digital wireframes',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Visual Design Section Divider =========================================================
  defineField({
    name: 'visualDesignSectionTitle',
    title: 'Visual Design Section Title',
    type: 'string',
    group: 'project-specific',
    description: 'Large heading to divide major sections (e.g., "VISUAL DESIGN")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'visualDesignSectionImage',
    title: 'Visual Design Section Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'visualDesignSectionVideo',
    title: 'Visual Design Section Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'visualDesignSectionVideoPoster',
    title: 'Visual Design Section Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for large image to divide major sections',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Style Guide / Design System Section =========================================================
  defineField({
    name: 'styleGuideHeading',
    title: 'Style Guide Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for style guide section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'styleGuideDescription',
    title: 'Style Guide Description',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text describing the design system and its components',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'styleGuideImages',
    title: 'Style Guide Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Images of style guide elements and components',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'styleGuideVideos',
    title: 'Style Guide Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos of style guide elements and components',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'styleGuideVideoPosters',
    title: 'Style Guide Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for videos of style guide elements and components',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== High Fidelity Designs Section =========================================================
  defineField({
    name: 'highFidelityHeading',
    title: 'High Fidelity Designs Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for high-fidelity mockups section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'highFidelityIntro',
    title: 'High Fidelity Introduction',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Introductory text explaining what screens are included',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyScreensList',
    title: 'Key Screens List',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Numbered list describing key screens and their features',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'highFidelityMockups',
    title: 'High Fidelity Mockups',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Images showing final UI designs across devices',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'highFidelityMockupsVideo',
    title: 'High Fidelity Mockups Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos showing final UI designs across devices',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'highFidelityMockupsVideoPoster',
    title: 'High Fidelity Mockups Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for videos showing final UI designs across devices',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== High Fidelity Prototypes Section =========================================================
  defineField({
    name: 'prototypeHeading',
    title: 'Prototype Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for prototype section (e.g., "High fidelity Prototypes")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeDescription',
    title: 'Prototype Description',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text describing what the prototype demonstrates',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeImages',
    title: 'Prototype Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Images showing the interactive prototype flows',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeVideos',
    title: 'Prototype Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos showing the interactive prototype flows',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeVideoPosters',
    title: 'Prototype Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'image', options: { hotspot: true } }],
    description: 'Optional fallback poster images for videos showing the interactive prototype flows',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeNotes',
    title: 'Prototype Notes',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of notes on the prototype and animations',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Prototype Validation Section =========================================================
  defineField({
    name: 'validationHeading',
    title: 'Validation Approach Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for validation section (e.g., "Prototype Validation Approach")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'validationDescription',
    title: 'Validation Description',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text describing the usability testing methodology',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'validationMethodology',
    title: 'Validation Methodology',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of testing approach details (participants, tasks, metrics)',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'studyResultsHeading',
    title: 'Study Results Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for results section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'studyResults',
    title: 'Study Results',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of key findings and metrics from testing',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'studyResultsImage',
    title: 'Study Results Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Photo or image accompanying the results',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'studyResultsVideo',
    title: 'Study Results Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Photo or image accompanying the results',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'studyResultsVideoPoster',
    title: 'Study Results Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for photo or image accompanying the results',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeUpdateHeading',
    title: 'Prototype Update Concept Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for updates section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeUpdates',
    title: 'Prototype Updates',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of changes made based on testing feedback',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeUpdatesImage',
    title: 'Prototype Update Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Photo or image accompanying prototype updates',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeUpdatesVideo',
    title: 'Prototype Update Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Photo or image accompanying prototype updates',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'prototypeUpdatesVideoPoster',
    title: 'Prototype Update Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for photo or image accompanying prototype updates',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Accessibility Considerations Section =========================================================
  defineField({
    name: 'accessibilityHeading',
    title: 'Accessibility Considerations Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for accessibility section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'accessibilityConsiderations',
    title: 'Accessibility Considerations',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of accessibility features and standards met',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'accessibilityMockup',
    title: 'Accessibility Mockup',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Annotated image showing accessibility features in the design',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'accessibilityMockupVideo',
    title: 'Accessibility Mockup Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Annotated image showing accessibility features in the design',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'accessibilityMockupVideoPoster',
    title: 'Accessibility Mockup Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for annotated image showing accessibility features in the design',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Final Thoughts / Takeaways Section =========================================================
  defineField({
    name: 'finalThoughtsSectionHeading',
    title: 'Final Thoughts Section Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Main heading for conclusion section (e.g., "FINAL THOUGHTS / TAKEAWAYS")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'finalThoughtsSectionImage',
    title: 'Final Thoughts Section Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Final Thoughts Section Image',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'finalThoughtsSectionVideo',
    title: 'Final Thoughts Section Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Final Thoughts Section Video',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'finalThoughtsSectionVideoPoster',
    title: 'Final Thoughts Section Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for final Thoughts Section Video',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'finalResultsHeading',
    title: 'Final Results Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Subheading for results (e.g., "Final Results & Expected Outcomes")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'finalResultsText',
    title: 'Final Results Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Paragraph summarizing the final design outcome',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'expectedOutcomes',
    title: 'Expected Outcomes',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of expected outcomes and impact',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'outcomesDisclaimer',
    title: 'Outcomes Disclaimer',
    type: 'text',
    group: 'project-specific',
    rows: 2,
    description: 'Disclaimer text about hypothetical outcomes (in parentheses)',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyLearningsHeading',
    title: 'Key Learnings Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for learnings section (e.g., "Key Learnings (Design + Product + Process)")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyLearnings',
    title: 'Key Learnings',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Bullet list of key takeaways and lessons learned',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyLearningsImage',
    title: 'Key Learnings Image',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Supporting image for the key learnings section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyLearningsVideo',
    title: 'Key Learnings Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Supporting image for the key learnings section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'keyLearningsVideoPoster',
    title: 'Key Learnings Video Poster',
    type: 'image',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for supporting image for the key learnings section',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Future Improvements Section =========================================================
  defineField({
    name: 'futureImprovementsHeading',
    title: 'Future Improvements Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for next steps section (e.g., "Future Improvements / Next Steps")',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'futureImprovements',
    title: 'Future Improvements',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: [
          { name: 'improvementTitle', title: 'Improvement Title', type: 'string', description: 'e.g., "Pharmacy integration", "Cross-device sync"' },
          { name: 'improvementDescription', title: 'Improvement Description', type: 'text', rows: 2, description: 'Description of what the improvement entails' },
        ],
      },
    ],
    description: 'List of future feature ideas and next steps',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),

  // ===== Closing Summary Section =========================================================
  defineField({
    name: 'closingSummaryHeading',
    title: 'Closing Summary Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for final summary',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
  defineField({
    name: 'closingSummaryText',
    title: 'Closing Summary Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Final paragraph summarizing the project and its value',
    hidden: ({ parent }) => parent?.categoryName !== 'UX Case Studies',
  }),
]
