// schemas/websiteFields.ts
import { defineField } from 'sanity'
import { makeTeaserFields, makeOutcomesFields, makeKeyLearningsFields, makeWhatWorkedFields, makeItemFields } from './shared/fieldGroups'

export const websiteFields = [
  // ===== Teaser Image Section =========================================================
  ...makeTeaserFields('website_', 'Websites'),

  // ===== Business Context ===============================================================
  defineField({
    name: 'website_businessContextHeading',
    title: 'Business Context Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Business Context section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_businessContextContent',
    title: 'Business Context Content',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text content explaining Business Context findings',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Problems Identified ===============================================================
  defineField({
    name: 'website_problemsIdentifiedHeading',
    title: 'Problems Identified Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Brand Problems identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_problemsIdentified',
    title: 'Problems Identified',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of Brand Problems identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_problemsIdentifiedImage',
    title: 'Problems Identified Image',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_problemsIdentifiedVideo',
    title: 'Problems Identified Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_problemsIdentifiedVideoPoster',
    title: 'Problems Identified Video Poster',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Problems Identified',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Design Objectives ===============================================================
  defineField({
    name: 'website_designObjectivesHeading',
    title: 'Design Objectives Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Brand Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_designObjectives',
    title: 'Design Objectives',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'List of Brand Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_designObjectivesImage',
    title: 'Design Objectives Image',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_designObjectivesVideo',
    title: 'Design Objectives Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_designObjectivesVideoPoster',
    title: 'Design Objectives Video Poster',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Design Objectives',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Market Context Section =========================================================
  defineField({
    name: 'website_marketContextHeading',
    title: 'Market Context Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for market context section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_marketContext',
    title: 'Market Context',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text explaining the project market context',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_targetAudienceHeading',
    title: 'Target Audeince Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Target Audience section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  defineField({
    name: 'website_targetAudience',
    title: 'Target Audience',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: [
          { name: 'member', title: 'Audience Member Title', type: 'string', description: 'e.g., "Athletes", "Investors"' },
          { name: 'rationale', title: 'Audience Member Rationale', type: 'text', rows: 2, description: 'Description of what this audience member needs' },
        ],
      },
    ],
    description: 'List of people who classify as tyhe target audience for this website',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Information Architecture Section =========================================================
  defineField({
    name: 'website_informationArcHeading',
    title: 'Information Architecture Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the Information Architecture section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_informationArcText',
    title: 'Information Architecture Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the Information Architecture section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_informationArcImages',
    title: 'Information Architecture Section Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Images for the information Architecture section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_informationArcVideos',
    title: 'Information Architecture Section Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos for the information Architecture section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_informationArcVideoPosters',
    title: 'Information Architecture Section Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for videos for the information Architecture section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== UX Structure & Planning ===============================================================
  defineField({
    name: 'website_uxStructureHeading',
    title: 'UX Structure Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for UX Structure section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_uxStructureText',
    title: 'UX Structure Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text content explaining UX Structure',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_uxStructureItems',
    title: 'UX Structure Breakdown',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: makeItemFields('structure', 'Structure'),
      },
    ],
    description: 'List of UX structure considerations with details',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Visual Design Section =========================================================
  defineField({
    name: 'website_visualDesignHeading',
    title: 'Visual Design Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the Visual Design section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_visualDesignText',
    title: 'Visual Design Section Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text for the Visual Design section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_visualDesignImages',
    title: 'Visual Design Section Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Images for the Visual design section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_visualDesignVideos',
    title: 'Visual Design Section Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos for the Visual design section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_visualDesignVideoPosters',
    title: 'Visual Design Section Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for videos for the Visual design section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Website Build & Implementation ===============================================================
  defineField({
    name: 'website_websiteBuildHeading',
    title: 'Website Build Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Website Build section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_websiteBuildText',
    title: 'Website Build Text',
    type: 'text',
    group: 'project-specific',
    rows: 3,
    description: 'Text content explaining Website Build',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_websiteBuildItems',
    title: 'Website Build Breakdown',
    type: 'array',
    group: 'project-specific',
    of: [
      {
        type: 'object',
        fields: makeItemFields('buildItem', 'Build Item'),
      },
    ],
    description: 'List of Website Build considerations with details',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_websiteBuildImages',
    title: 'Website Build Section Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Images for the Website Build section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_websiteBuildVideos',
    title: 'Website Build Section Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos for the Website Build section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_websiteBuildVideoPosters',
    title: 'Website Build Section Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for videos for the Website Build section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Accessibility Section =========================================================
  defineField({
    name: 'website_accessibilityHeading',
    title: 'Accessibility Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for the Accessibility section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_accessibilityText',
    title: 'Accessibility Section Considerations',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Text/list for the Accessibility section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_accessibilityImages',
    title: 'Accessibility Section Images',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Images for the Accessibility section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_accessibilityVideos',
    title: 'Accessibility Section Videos',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'file', options: { accept: 'video/mp4,video/webm' } }],
    description: 'Videos for the Accessibility section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_accessibilityVideoPosters',
    title: 'Accessibility Section Video Posters',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'imageWithAlt' }],
    description: 'Optional fallback poster images for videos for the Accessibility section',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Pre-Launch ===============================================================
  defineField({
    name: 'website_preLaunchHeading',
    title: 'Pre-Launch Heading',
    type: 'string',
    group: 'project-specific',
    description: 'Heading for Website Pre-Launch',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_preLaunchChecks',
    title: 'Pre-Launch Checks',
    type: 'array',
    group: 'project-specific',
    of: [{ type: 'string' }],
    description: 'Website Pre-Launch Checklist',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_preLaunchImage',
    title: 'Pre-Launch Image',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Image supporting Pre-Launch',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_preLaunchVideo',
    title: 'Pre-Launch Video',
    type: 'file',
    group: 'project-specific',
    options: { accept: 'video/mp4,video/webm' },
    description: 'Video supporting Pre-Launch',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),
  defineField({
    name: 'website_preLaunchVideoPoster',
    title: 'Pre-Launch Video Poster',
    type: 'imageWithAlt',
    group: 'project-specific',
    options: { hotspot: true },
    description: 'Optional fallback poster image for video supporting Pre-Launch',
    hidden: ({ parent }) => parent?.categoryName !== 'Websites',
  }),

  // ===== Outcomes Section =========================================================
  ...makeOutcomesFields('website_', 'Websites'),

  // ===== Key Learnings Section ===============================================================
  ...makeKeyLearningsFields('website_', 'Websites'),

  // ===== What Worked Section ===============================================================
  ...makeWhatWorkedFields('website_', 'Websites'),
]
